#PostgreSQL (Supabase) connection helpers and schema creation.
import os

import psycopg
from psycopg.rows import dict_row

NO_ID = {"incident_people", "sessions"}  # tables that have no integer id column

FIXED_SCHEMA = [
    "create table if not exists users(id integer generated by default as identity primary key, username text unique not null, name text not null, role text not null, pw_hash text not null)",
    "create table if not exists sessions(token text primary key, user_id integer not null references users(id) on delete cascade, expires bigint not null)",
    "create table if not exists custody(id integer generated by default as identity primary key, cargo_id integer not null references cargo(id) on delete cascade, ts bigint not null, status text not null, location text, handler text, note text)",
    "create table if not exists incident_people(incident_id integer not null references incidents(id) on delete cascade, personnel_id integer not null references personnel(id) on delete cascade, primary key(incident_id, personnel_id))",
    "create table if not exists incident_actions(id integer generated by default as identity primary key, incident_id integer not null references incidents(id) on delete cascade, ts bigint not null, action text not null, assignee text, status text not null default 'Pending')",
    "create table if not exists audit(id integer generated by default as identity primary key, ts bigint not null, actor text not null, action text not null, entity text, entity_id integer, detail text)",
]

class Connection:
    #Thin wrapper over a psycopg connection.

    def __init__(self, raw):
        self.raw = raw

    def execute(self, sql, args=()):
        return self.raw.execute(sql.replace("?", "%s"), list(args) or None)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()

def connect():
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set. Use your Supabase connection string.")
    # prepare_threshold=None turns off prepared statements, which Supabase's transaction pooler does not support.
    return Connection(psycopg.connect(url, row_factory=dict_row, prepare_threshold=None, connect_timeout=10))

def rows(conn, sql, args=()):
    return [dict(r) for r in conn.execute(sql, args)]

def one(conn, sql, args=()):
    r = conn.execute(sql, args).fetchone()
    return dict(r) if r else None

def insert(conn, table, values):
    cols = list(values)
    sql = f"insert into {table}({','.join(cols)}) values({','.join('?' * len(cols))})"
    if table in NO_ID:
        conn.execute(sql, [values[k] for k in cols])
        return None
    return conn.execute(sql + " returning id", [values[k] for k in cols]).fetchone()["id"]

def create_schema(conn):
    from .entities import ddl  # imported here to avoid a circular import
    for stmt in [*ddl(), *FIXED_SCHEMA]:
        conn.execute(stmt)
